linfenyancao/linfenyancao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shiju import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 市局
    path('shiju/', views.shiju, name='shiju'),
    # 领导
    path('lingdao/',views.lingdao, name='领导班子'),
    # 文章列表
    path('list/<int:pk>/', views.artical_list, name='articallist'),
    # 文章细节页面
    path('artical/<int:pk>/',views.artical, name='artical'),

    # 县局页面
    path('xianju/<int:pk>/',views.xianju, name="xianju"),
    path('keshi/<int:pk>/',views.keshi,name='keshi'),
    path('keshi/teshu/',views.teshu_keshi,name='teshukeshi'),


    # dwebcms登录
    # path('cms/login',views.cms_login, name='登录'),
    # dwebcms管理首页
    path('cms/index/',views.cms_index, name='管理首页'),
    # dwebcms新建栏目
    path('cms/newlanmu',views.cms_newLanmu, name='newLanmu'),
    # dwebcms栏目列表
    path('cms/listlanmu',views.cms_listLanmu, name='listLanmu'),
    # dwebcms删除子栏目
    path('cms/sublanmu/<int:pk>/delete/',views.cms_deleteSubLanmu, name="删除子栏目"),
    path('cms/sublanmu/<int:pk>/zhiding/',views.cms_zhidingSubLanmu, name="zhiding"),

    # dwebcms文章发布
    path('cms/wztijiao/<str:jigou_name>/',views.cms_wzTijiao, name="wzTijiao"),
    # dwebcms文章列表
    path('cms/wzlist/',views.cms_wzList, name="wzList"),
    # dwebcms文章删除
    path('cms/wzdelete/<int:pk>/',views.cms_wzDelete, name="wzDelete"),

    # dwebcms文章还原
    path('cms/wzhuanyuan/<int:pk>/',views.cms_wzHuanyuan, name="wzHuanyuan"),

    # dwebcms文章修改
    path('cms/wzxiugai/<int:pk>/',views.cms_wzXiugai, name="wzXiugai"),
    # dwebcms文章回收
    path('cms/wzhuishou/',views.cms_wzHuishou, name="wzHuishou"),

    # dwebcms文章彻底删除
    path('cms/wzhuishou/<int:pk>/',views.cms_wzDelete_cd, name='wzDelete_cd'),

    # dwebcoms增加人员
    path('cms/renyuan/add/',views.cms_addRenYuan, name='addRenYuan'),
    path('cms/renyuan/list/',views.cms_listRenYuan,name='listRenYuan'),

    # accounts
    path('accounts/', include('django.contrib.auth.urls')),

    # 默认
    path('', views.shiju, ),
    # 富文本
    path('ueditor/', include('DjangoUeditor.urls' ) ),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

linfenyancao/shiju/models.py
from datetime import date

from django.db import models
from django.urls import reverse
from django.shortcuts import  get_object_or_404, redirect
from django.contrib.auth.models import User

from DjangoUeditor.models import UEditorField

# Create your models here.
class Jigou(models.Model):
    name = models.CharField(default='',blank=True,null=True,max_length=255)
    telephone = models.CharField(default='',blank=True,null=True,max_length=255)
    email = models.CharField(default='',blank=True,null=True,max_length=255)
    daihao = models.CharField(default='',blank=True,null=True,max_length=255)

    class Meta:
        ordering = ['daihao']

    def __str__(self):
        return '%s%s' % (self.daihao,self.name)

    def get_sub_lanmu(self):
        return self.lanmu_set.all()

    def get_sup_lanmu(self):
        return self.suplanmu_set.all()

    def get_all_articals(self):
        articals = []
        for lanmu in self.get_sub_lanmu():
            for artical in lanmu.get_all_articals():
                articals.append(artical)
        return articals

    def get_all_undelete_articals(self):
        articals = []
        for lanmu in self.get_sub_lanmu():
            for artical in lanmu.get_all_undelete_articals():
                articals.append(artical)
        return articals

    def get_all_deleted_articals(self):
        articals = []
        for lanmu in self.get_sub_lanmu():
            for artical in lanmu.get_all_deleted_articals():
                articals.append(artical)
        return articals

    def get_absolute_url(self):
        return reverse('xianju',args=[self.pk])

    def get_xianju_url(self):
        return reverse('xianju',args=[self.pk])

    def get_keshi_url(self):
        return reverse('keshi',args=[self.pk])

    def is_xianju(self):
        return "县" in self.name


class Suplanmu(models.Model):
    name = models.CharField(default='',blank=True,null=True,max_length=255)
    jigou = models.ForeignKey(Jigou, on_delete=models.CASCADE,blank=True, null=True)

    def __str__(self):
        return '%s' % (self.name)

    def get_sub_lanmu(self):
        return self.sub_lanmu.all()

    def get_all_articals(self):
        articals = []
        for lanmu in self.get_sub_lanmu():
            for artical in lanmu.get_all_articals():
                articals.append(artical)
        return articals

    def get_all_undelete_articals(self):
        articals = []
        for lanmu in self.get_sub_lanmu():
            for artical in lanmu.get_all_undelete_articals():
                articals.append(artical)
        return articals

    def get_all_deleted_articals(self):
        articals = []
        for lanmu in self.get_sub_lanmu():
            for artical in lanmu.get_all_deleted_articals():
                articals.append(artical)
        return articals




class Lanmu(models.Model):
    name = models.CharField(max_length=255, default='')
    jigou = models.ForeignKey(Jigou, on_delete=models.CASCADE,blank=True, null=True)
    sup_lanmu = models.ForeignKey(Suplanmu,on_delete=models.CASCADE,related_name='sub_lanmu',blank=True,null=True)
    zhiding = models.BooleanField(default=False)


    def __str__(self):
        return '%s%s' % (self.jigou.name,self.name)

    def get_all_articals(self):
        return self.artical_set.all()

    def get_all_undelete_articals(self):
        return self.artical_set.filter(huishou=False)

    def get_all_deleted_articals(self):
        return self.artical_set.filter(huishou=True)

    def get_first_ten_articals(self):
        if len(self.get_all_undelete_articals()) > 10:
            return self.get_all_undelete_articals()[:10]
        else:
            return self.get_all_undelete_articals()

    def is_zhiding(self):
        if self.zhiding:
            return True
        else:
            return False

    def get_absolute_url(self):
        return reverse('articallist',args=[self.pk,])


class Artical(models.Model):
    biaoti = models.CharField(max_length=255, default='')
    neirong = UEditorField(u'内容	', width=600, height=300, toolbars="full", imagePath="",filePath="",upload_settings={"imageMaxSize":1204000},settings={}, command=None,blank=True)
    fabiao_riqi = models.DateTimeField(auto_now_add=True, null=True)
    image = models.ImageField(default='', blank=True)
    yuedu = models.PositiveIntegerField(default=0,)
    dianzan = models.PositiveIntegerField(default=0,)
    file = models.FileField(default='',blank=True)
    lanmu = models.ForeignKey(Lanmu, on_delete=models.CASCADE)
    huishou = models.BooleanField(default=False)

    class Meta:
        ordering = ['-fabiao_riqi']

    def __str__(self):
        return '%s' % self.biaoti

    def get_absolute_url(self):
        return reverse('artical',args=(self.pk,))

    def get_delete_url(self):
        return reverse('wzDelete',args=(self.pk,))

    def is_huishou(self):
        if self.huishou:
            return True
        else:
            return False

    def get_delete_cd_url(self):
        return reverse('wzDelete_cd',args=(self.pk,))


class Profile(models.Model):
    ZHI_BAN_DATE = (
        ('0','星期一'),
        ('1','星期二'),
        ('2','星期三'),
        ('3','星期四'),
        ('4','星期五'),
        ('5','星期六'),
        ('6','星期日'),
        ('7','无'),
    )
    user = models.OneToOneField(User,on_delete=models.CASCADE,blank=True, null=True)
    display_name = models.CharField(default='',max_length=100)
    zhiwei = models.CharField(default='',max_length=100)
    zhiban_date = models.CharField(max_length=10,
                                   choices=ZHI_BAN_DATE,
                                   default='7',)
    jigou = models.ForeignKey(Jigou, on_delete=models.CASCADE,blank=True, null=True)
    telephone = models.CharField(default='',max_length=100)

    def __str__(self):
        return '%s' % self.display_name

    @property
    def is_zhiban(self):
        return int(self.zhiban_date) == date.today().weekday()

linfenyancao/shiju/forms.py
from django import forms

from .models import Lanmu, Artical, Profile

from DjangoUeditor.forms import UEditorField

class LanmuForm(forms.Form):
    name = forms.CharField()
    jigou_name = forms.CharField(required=False)
    sup_lanmu_name = forms.CharField(required=False)


class ArticalForm(forms.Form):
    biaoti = forms.CharField()
    lanmu_name = forms.CharField()
    file = forms.FileField(required=False)
    neirong = UEditorField(u'内容	', width=960, height=500, toolbars="full",
    imagePath="",filePath="",upload_settings={"imageMaxSize":12040000})


class ProfileForm(forms.Form):
    display_name = forms.CharField()
    jigou_name = forms.CharField()
    telephone = forms.CharField()
    zhiban_date = forms.CharField()

linfenyancao/shiju/templates/dwebcms/listLanmu.html
{% extends "dwebcms/index.html" %}
{% block webRight %}
<div class=" content-area">
	<div class="page-header">
		<h4 class="page-title">栏目列表</h4>
  </div>
	<div class="row row-deck">
		<div class="col-md-6">
			<div class="card">
				<div class="card-header">
					<h3 class="card-title">所有市局栏目</h3>
				</div>
				<div class="card-body">
					<div class="panel-group" id="accordion1" role="tablist" aria-multiselectable="true">
            {% for dj_lanmu in dj_lanmus %}
  						<div class="panel panel-default mt-2">
  							<div class="panel-heading" role="tab" id="leftList{{ dj_lanmu.pk }}">
  								<h4 class="panel-title">
  									<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion1" href="#lanmu{{ dj_lanmu.pk }}" aria-expanded="false" aria-controls="lanmu{{ dj_lanmu.pk }}">
  										{{ dj_lanmu.name }}

  									</a>
  								</h4>
  							</div>
  							<div id="lanmu{{ dj_lanmu.pk }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="leftList{{ dj_lanmu.pk }}">
                  <div class="card-body">
  									<ul class="list-group">
                      {% for sub_lanmu in dj_lanmu.get_sub_lanmu  %}
                        <li class="list-group-item justify-content-between">
    										{{ sub_lanmu.name }}
    										<span class="badgetext badge badge-danger badge-pill">
                          <a href="{% url '删除子栏目' sub_lanmu.pk %}" style="color:#fff;font-weight: 500;">删除该栏目</a>
                        </span>
    										</li>
                      {% empty %}
                        <li class="list-group-item justify-content-between">
                        无下级
                        </li>
                      {% endfor %}
                    </ul>
  								</div>
  							</div>
  						</div>
            {% empty %}
              <div class="panel panel-default mt-2">
                <div class="panel-heading" role="tab" id="leftListNone">
                  <h4 class="panel-title">
                    <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion1" href="#lanmuNone" aria-expanded="false" aria-controls="lanmuNone">
                      无栏目
                    </a>
                  </h4>
                </div>
              </div>
            {% endfor %}
					</div><!-- panel-group -->
				</div>
			</div>
		</div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">所有机构栏目</h3>
          
        </div>
        <div class="card-body">
          <div class="panel-group1" id="accordion2">
            {% for jigou in jigous %}
            {% if jigou.name != "临汾市局" %}
              <div class="panel panel-default mb-4">
              <div class="panel-heading1 ">
                <h4 class="panel-title1">
                  <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion2" href="#jigou{{ jigou.pk }}" aria-expanded="false">{{ jigou.name }}</a>
                </h4>
              </div>
              <div id="jigou{{ jigou.pk }}" class="panel-collapse collapse" role="tabpanel" aria-expanded="false">
                <div class="card-body">
                  <ul class="list-group">

                      {% for sub_lanmu in jigou.get_sub_lanmu %}
                      <li class="list-group-item justify-content-between">
                      {{ sub_lanmu.name }}
                      <span class="badgetext badge badge-danger badge-pill">
                        <a href="{% url '删除子栏目' sub_lanmu.pk %}" style="color:#fff;font-weight: 500;">删除</a>
                      </span>
                      {% if jigou.is_xianju %}
                        {% if sub_lanmu.is_zhiding %}
                          <span class="badgetext badge badge-success badge-pill">
                            <a href="{% url 'zhiding' sub_lanmu.pk %}" style="color:#fff;font-weight: 500;">取消置顶</a>
                          </span>
                        {% else %}
                          <span class="badgetext badge badge-danger badge-pill">
                            <a href="{% url 'zhiding' sub_lanmu.pk %}" style="color:#fff;font-weight: 500;">置顶</a>
                          </span>
                        {% endif %}
                        
                      {% endif %}
                      </li>
                      {% empty %}
                        <li class="list-group-item justify-content-between">
                        无子栏目
                        </li>
                      {% endfor %}

                  </ul>
                </div>
              </div>

            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

linfenyancao/shiju/templates/dwebcms/newLanmu.html
{% extends "dwebcms/index.html" %}
{% block webRight %}
  <div class=" content-area">
		<div class="page-header">
			<h4 class="page-title">新建栏目</h4>
    </div>

		 <div class="row">

			<!-- end col -->
			<div class="col-xl-6">
				<div class="card m-b-20">
					<div class="card-header">
						<h3 class="card-title">网站栏目新建</h3>

					</div>
					<div class="card-body mb-0">
						<form class="form-horizontal" method="POST" action="">
							{% csrf_token %}
							<div class="form-group ">
								<div class="row">
									<ul>
										{{ error_message }}
									</ul>
								</div>
								<div class="row">
									<div class="col-md-3">
										<label class="form-label" id="examplenameInputname2">栏目名称</label>
									</div>
									<div class="col-md-9">
										<input name="name" type="text" class="form-control" id="examplenameInputname3"  placeholder="输入栏目名称" required="required">
									</div>
								</div>
							</div>
              <div class="form-group ">
								<div class="row">
									<div class="col-md-3">
										<label class="form-label">选择所属机构</label>
									</div>
									<div class="col-md-9">
										<select id="jigou"  name="jigou_name" class="form-control"  oninput="OnInput (event)" onpropertychange="OnPropChanged (event)">

											{% for jigou in jigous %}
												<option value="{{ jigou.name }}" >{{ jigou.name }}</option>
											{% endfor %}

										</select>
									</div>
								</div>
							</div>
              <div class="form-group ">
								<div class="row">
									<div class="col-md-3">
										<label class="form-label">选择顶级栏目</label>
									</div>
									<div id="suplanmu" class="col-md-9">
										<select name="sup_lanmu_name" class="form-control">

											{% for sup_lanmu in sup_lanmus %}
												<option value="{{ sup_lanmu.name }}">{{ sup_lanmu.name }}</option>
											{% endfor %}

										</select>
									</div>
                  <div id="suplanmu2" class="col-md-9" style="display:none;">
									  非市局机构，无需选择
									</div>
								</div>
							</div>
							<div class="form-group mb-0 row justify-content-end">
								<div class="col-md-9 float-right">
									<button type="submit" class="btn btn-primary waves-effect waves-light">提交</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<!-- end row -->
  </div>

  <script type="text/javascript">
  // Firefox, Google Chrome, Opera, Safari, Internet Explorer from version 9
    function OnInput (event) {
      //alert ("The new content: " + event.target.value);
      var value = event.target.value;
      changeJigou(value);
    }
  // Internet Explorer
    function OnPropChanged (event) {
      if (event.propertyName.toLowerCase () == "value") {
        var value = event.srcElement.value;
        changeJigou(value);
      }
    }

    function changeJigou(value){
			var jigou = document.getElementById('jigou').value;
			if(jigou != '临汾市局'){
        document.getElementById("suplanmu2").style.display="block";
        document.getElementById("suplanmu").style.display="none";
			}else{
        document.getElementById("suplanmu2").style.display="none";
        document.getElementById("suplanmu").style.display="block";
      }
		}
  </script>

{% endblock %}

linfenyancao/shiju/templates/dwebcms/userList.html
{% extends "dwebcms/index.html" %}

{% block webRight %}

<div class=" content-area">
  <div class="page-header">
    <h1 class="page-title">所有人员</h1>
  </div>
  <div class="row ">
    <div class="col-lg-12">
      <div class="input-group mb-3">
        <input type="text" class="form-control br-tl-7 br-bl-7" placeholder="">
        <div class="input-group-append ">
          <button type="button" class="btn btn-white br-tr-7 br-br-7">
            <i class="fa fa-search" aria-hidden="true"></i>
          </button>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <div class="table-responsive border-top">
            <table class="table card-table table-bordered table-hover table-vcenter">
              <tbody>

              <tr>
                <th class="w-1">名字</th>
                <th class="w-1">值班日期</th>
                <th>所属机构</th>
                <th>手机</th>
                <th>电话</th>
                <th>账号密码</th>
              </tr>
                {% for item  in renyuan_list %}
                <tr>
                <th>
                  {{item.display_name}}
                </th>
                <td>
                  {{item.get_zhiban_date_display}}
                </td>
                <td>{{item.jigou.name}}</td>
                <td class="">{{item.telephone}}</td>
                <td>
                    {{item.telephone}}
                </td>
                <td>
                  <div class="item-action dropdown">
                    <a href="javascript:void(0)" data-toggle="dropdown" class="icon"><i class="fe fe-more-vertical fs-20 text-dark"></i></a>
                    <div class="dropdown-menu dropdown-menu-right">
                      <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-tag"></i> 添加账号绑定 </a>
                      <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-edit-2"></i> 删除 </a>
                      <a href="javascript:void(0)" class="dropdown-item"><i class="dropdown-icon fe fe-hard-drive"></i> 提交保存</a>

                    </div>
                  </div>
                </td>
              </tr>
                  
                {% endfor %}
              

              </tbody>
            </table>
          </div>
        </div>
      </div>
      <ul class="pagination mb-5">
        <li class="page-item page-prev disabled">
          <a class="page-link" href="#" tabindex="-1">上一页</a>
        </li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">4</a></li>
        <li class="page-item"><a class="page-link" href="#">5</a></li>
        <li class="page-item page-next">
          <a class="page-link" href="#">下一页</a>
        </li>
      </ul>
    </div>
  </div>
</div>




{% endblock %}

linfenyancao/shiju/templates/dwebcms/wzTijiao.html
{% extends "dwebcms/index.html" %}

{% block webRight %}


<div class=" content-area">
  <div class="page-header">
    <h4 class="page-title">文章发布</h4>
  </div>
  <div class="row">



    <div class="col-12">
      <div   class="card">
        <div class="card-header">
          <h3 class="card-title">填写文章详细内容</h3>

        </div>




        <form id="tijiao" method="POST" enctype="multipart/form-data">


        <div class="card-body">
          <div class="row">


            <div class="col-md-12 col-lg-12">
              <div class="form-group">
                <label class="form-label">文章标题</label>
                <input id="id_biaoti" type="text" class="form-control" name="biaoti" placeholder="输入文章标题">
              </div>
              <div class="form-group col-md-4 col-lg-4">
                <label class="form-label"> 所属机构</label>
                <select class="form-control select2-show-search" data-placeholder="Choose one (with searchbox)" onchange="javascript:location.href=this.value;">
                    <option value="{% with jigou.name as jigou_name %}
                        {% url 'wzTijiao' jigou_name=jigou_name %}
                    {% endwith %} ">
                      {{ jigou.name }}
                    </option>
                  {% for item in jigous %}
                    {% if item.name != jigou.name %}
                      <option value="{% with item.name as jigou_name %}
                          {% url 'wzTijiao' jigou_name=jigou_name %}
                      {% endwith %} ">
                        {{ item.name }}
                      </option>
                    {% endif %}
                  {% endfor %}
                </select>
              </div>
              <div class="form-group col-md-4 col-lg-4">
                <label class="form-label"> 发布栏目</label>
                {% if jigou.get_sub_lanmu %}
                <select id="id_lanmu_name" name="lanmu_name" class="form-control select2-show-search" data-placeholder="Choose one (with searchbox)" required>
                  {% for lanmu in jigou.get_sub_lanmu %}
                  <option value="{{ lanmu.name }}">{{ lanmu.name }}</option>
                  {% endfor %}
                </select>
                {% else %}
                <span>
                  <a href="{% url 'newLanmu' %}">请先为机构新建一个栏目！</a>
                </span>
                {% endif %}
              </div>
              <div class="form-group col-md-4 col-lg-4">
                <div class="form-label">文档文件上传</div>
                <div class="custom-file">
                  <input id="id_file" type="file" class="" name="file">

                  {% csrf_token %}
                  <button style="margin-top:30px;" class="btn btn-primary ml-auto" onclick="yulan()">预览模式开启</button>
                  <div class="form-group" style="margin-top:10px;">
                      <span >开启一次即可，无需二次同步</span>

                  </div>


                </div>
              </div>

              <div class="form-group" style="margin-top:30px">
                <label class="form-label">文章内容</label>
                {{ form.neirong }}
              </div>




            </div>
          </div>
        </div>
        <div class="card-footer text-right">
          <div class="d-flex">

              {% csrf_token %}
            <button type="submit" class="btn btn-primary ml-auto" onclick="tijiao()" >提交发布</button>



            <script type="text/javascript">
            function yulan(){
              var aaa = document.getElementById("tijiao"); aaa.action="http://fileup.dweb.club/yancaoupload/";
              aaa.submit();
             }

             function tijiao() {
              var aaa = document.getElementById("tijiao");
              aaa.action="{% url 'wzTijiao' jigou_name=jigou.name %}";
              aaa.submit();
            }


            </script>


          </div>
        </div>



        </form>

      </div>

      <div class="card" style="display:none;">
        <div class="card-header">
          <h3 class="card-title">File Uploads</h3>
          <div class="card-options">
            <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
            <a href="#" class="card-options-remove" data-toggle="card-remove"><i class="fe fe-x"></i></a>
          </div>
        </div>
        <div class=" card-body">
          <div class="row">
            <div class="col-lg-4 col-sm-12">
              <input type="file" class="dropify" data-height="180" />
            </div>
            <div class="col-lg-4 col-sm-12">
              <input type="file" class="dropify" data-default-file="assets/images/media/media1.jpg" data-height="180"  />
            </div>
            <div class="col-lg-4 col-sm-12">
              <input type="file" class="dropify" disabled="disabled" data-height="180" />
            </div>
          </div>
          <br>
          <div class="form-group">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="example-file-input-custom">
              <label class="custom-file-label">Choose file</label>
            </div>
          </div>
        </div>
      </div>
    </div>


  </div>
</div>


{% endblock %}

linfenyancao/shiju/templates/dwebcms/wzXiugai.html
{% extends "dwebcms/index.html" %}
{% block webRight %}
<div class=" content-area">
  <div class="page-header">
    <h4 class="page-title">文章发布</h4>
  </div>
  <div class="row">
    <div class="col-12">
      <div   class="card">
        <div class="card-header">
          <h3 class="card-title">填写文章详细内容</h3>

        </div>
        <form method="POST" enctype="multipart/form-data" action="{% url 'wzXiugai' artical.pk %}">
          {% csrf_token %}
        <div class="card-body">
          <div class="row">
            <div class="col-md-12 col-lg-12">
              <div class="form-group">
                <label class="form-label">文章标题</label>
                <input id="id_biaoti" type="text" class="form-control" name="biaoti" placeholder="{{ artical.biaoti }}" value="{{ artical.biaoti }}">
              </div>
              <div class="form-group col-md-4 col-lg-4">
                <label class="form-label"> 所属机构</label>
                <select class="form-control select2-show-search" data-placeholder="Choose one (with searchbox)">
                  <option value="0">{{ artical.lanmu.jigou.name }}</option>
                </select>
              </div>
              <div class="form-group col-md-4 col-lg-4">
                <label class="form-label"> 发布栏目</label>
                <select name="lanmu_pk" class="form-control select2-show-search" data-placeholder="Choose one (with searchbox)">
                  <option value="artical.lanmu.pk">{{ artical.lanmu.name }}</option>
                </select>
              </div>

              <div class="form-group">
                <label class="form-label">文章内容</label>
                
                {{ form.neirong }}
                <script type="text/javascript">
                  var ue = UE.getEditor('id_neirong',{
                      serverUrl: "/ueditor/",
                      initialFrameWidth : 960,
                      initialFrameHeight: 500,
                  });
                  ue.ready(function(){
                    //显示默认内容
                    ue.setContent('{{ artical.neirong|safe|escape }}')
                  })
              </script>
              </div>
            </div>
          </div>
        </div>
        <div class="card-footer text-right">
          <div class="d-flex">

            <button type="submit" class="btn btn-primary ml-auto">提交发布</button>
          </div>
        </div>
      </form>
      </div>
      <div class="card" style="display:none;">
        <div class="card-header">
          <h3 class="card-title">File Uploads</h3>
          <div class="card-options">
            <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
            <a href="#" class="card-options-remove" data-toggle="card-remove"><i class="fe fe-x"></i></a>
          </div>
        </div>
        <div class=" card-body">
          <div class="row">
            <div class="col-lg-4 col-sm-12">
              <input type="file" class="dropify" data-height="180" />
            </div>
            <div class="col-lg-4 col-sm-12">
              <input type="file" class="dropify" data-default-file="assets/images/media/media1.jpg" data-height="180"  />
            </div>
            <div class="col-lg-4 col-sm-12">
              <input type="file" class="dropify" disabled="disabled" data-height="180" />
            </div>
          </div>
          <br>
          <div class="form-group">
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="example-file-input-custom">
              <label class="custom-file-label">Choose file</label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}